# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the VRED Integration when it
# is running in its site level configuration

includes:
- ../common/engines.yml
- ../common/apps.yml
- apps.yml

vred.site:
  apps:

    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-pythonconsole: '@common.apps.tk-multi-pythonconsole'

    tk-multi-loader2:
      action_mappings:
        Alias File: [import, import_with_options, smart_reference]
        Igs File: [import, import_with_options, smart_reference]
        Stp File: [import, import_with_options, smart_reference]
        Stl File: [import, import_with_options, smart_reference]
        Jt File: [import, import_with_options, smart_reference]
        Catpart File: [import, import_with_options, smart_reference]
        Fbx File: [import, import_with_options, smart_reference]
        Motion Builder FBX: [import, import_with_options, smart_reference]
        VRED Scene: [import, import_with_options, smart_reference]
        Osb File: [import, import_with_options, smart_reference]
        Image: [import_sceneplate]
        Rendered Image: [import_sceneplate]
      actions_hook: "{engine}/tk-multi-loader2/basic/scene_actions.py"
      entities:
      - caption: Project
        type: Hierarchy
        root:
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [task_assignees, is, '{context.user}']
        hierarchy: [project, entity, content]
      # ignore publishes without a status. with zero config, it is very easy
      # to publish the same path multiple times. the default zero config publish
      # plugins will clear the status of previous publishes of the same path.
      # this filter means only the latest publish will be displayed.
      publish_filters: [["sg_status_list", "is_not", null]]
      location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel: '@vred.apps.tk-multi-shotgunpanel'

    tk-multi-data-validation: '@vred.apps.tk-multi-data-validation'

  location: "@common.engines.tk-vred.location"
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  - {app_instance: tk-multi-pythonconsole, name: 'Flow Production Tracking Python Console...'}
  docked_apps:
    tk-multi-shotgunpanel:
        pos: right
        tabbed: True
    tk-multi-pythonconsole:
        pos: right
        tabbed: True
  launch_builtin_plugins: [basic]
  automatic_context_switch: false
