# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Photoshop Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/engines.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


photoshopcc.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-pythonconsole: '@common.apps.tk-multi-pythonconsole'

    tk-multi-publish2:
      help_url: "@common.apps.tk-multi-publish2.help_url"
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/photoshopcc.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.file_publisher'
        - '@common.settings.tk-multi-publish2.version_creator'
        - name: Photoshop Document Publisher
          hook: "{config}/tk-multi-publish2/photoshopcc.basic/document_publisher.py"
          settings: {}
        - name: Send document to Shotgun review
          hook: "{config}/tk-multi-publish2/photoshopcc.basic/version_creator.py"
          settings: {}
        - name: Save the file to the next version
          hook: "{config}/tk-multi-publish2/photoshopcc.basic/version_up.py"
          settings: {}
      location: "@common.apps.tk-multi-publish2.location"

    tk-multi-loader2:
      action_mappings:
        Photoshop Image: [add_as_a_layer, open_file]
        Rendered Image: [add_as_a_layer, open_file]
        Image: [add_as_a_layer, open_file]
        Texture: [add_as_a_layer, open_file]
      actions_hook: '{self}/tk-photoshopcc_actions.py'
      entities:
      - caption: Current Project
        type: Hierarchy
        root: "{context.project}"
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [project, is, '{context.project}']
        - [task_assignees, is, '{context.user}']
        hierarchy: [entity, content]
      # ignore publishes without a status. with zero config, it is very easy
      # to publish the same path multiple times. the default zero config publish
      # plugins will clear the status of previous publishes of the same path.
      # this filter means only the latest publish will be displayed.
      publish_filters: [["sg_status_list", "is_not", null]]
      location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel:
      shotgun_fields_hook: '{self}/shotgun_fields.py'
      actions_hook: '{self}/general_actions.py'
      action_mappings:
        PublishedFile:
        - actions: [publish_clipboard]
          filters: {}
        - actions: [add_as_a_layer, open_file]
          filters: {published_file_type: Photoshop Image}
        - actions: [add_as_a_layer, open_file]
          filters: {published_file_type: Rendered Image}
        - actions: [add_as_a_layer, open_file]
          filters: {published_file_type: Image}
        - actions: [add_as_a_layer, open_file]
          filters: {published_file_type: Texture}
        Task:
        - actions: [assign_task, task_to_ip]
          filters: {}
        Version:
        - actions: [quicktime_clipboard, sequence_clipboard]
          filters: {}
      enable_context_switch: true
      location: "@common.apps.tk-multi-shotgunpanel.location"

  shelf_favorites: []
  debug_logging: true
  location: "@common.engines.tk-photoshopcc.location"

