# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Photoshop Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/apps.yml


photoshopcc.site:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-loader2:
      action_mappings:
        Photoshop Image: [add_as_a_layer, open_file]
        Rendered Image: [add_as_a_layer, open_file]
        Image: [add_as_a_layer, open_file]
      actions_hook: '{self}/tk-photoshopcc_actions.py'
      entities:
      - caption: Project
        type: Hierarchy
        root: /
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [task_assignees, is, '{context.user}']
        hierarchy: [project, entity, content]
      location:
        path: https://github.com/shotgunsoftware/tk-multi-loader2.git
        version: c6cfb186fcebd59d6ca933ce61835b797de44f21
        type: git_branch
        branch: develop/zero_config

    tk-multi-shotgunpanel:
      location:
        version: v1.2.7
        type: app_store
        name: tk-multi-shotgunpanel
      shotgun_fields_hook: '{self}/shotgun_fields.py'
      actions_hook: '{self}/general_actions.py'
      action_mappings:
        PublishedFile:
        - actions:
          - publish_clipboard
          filters: {}
        Task:
        - actions:
          - assign_task
          - task_to_ip
          filters: {}
        Version:
        - actions:
          - quicktime_clipboard
          - sequence_clipboard
          filters: {}

  shelf_favorites: []
  debug_logging: true
  location:
    path: https://github.com/shotgunsoftware/tk-photoshopcc.git
    version: ce1d2dc901586cd580440647b4fb94cf7f970aa1
    type: git_branch
    branch: develop/zero_config
