# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


maya.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/maya.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.file_publisher'
        - '@common.settings.tk-multi-publish2.version_creator'
        - name: Publish Maya File
          hook: "{config}/tk-multi-publish2/maya.basic/file_publisher.py"
          settings: {}
        - name: Publish current Maya Scene
          hook: "{config}/tk-multi-publish2/maya.basic/file_publisher.py:{config}/tk-multi-publish2/maya.basic/scene_publisher.py"
          settings: {}
        - name: Playblast to Shotgun Review
          hook: "{config}/tk-multi-publish2/maya.basic/playblast_version_creator.py"
          settings: {}
        - '@common.settings.tk-multi-publish2.alembic_publisher'
      location:
        #type: app_store
        #name: tk-multi-publish2
        #version: v0.0.10
        type: dev
        path: /Users/josh/dev/sg/zero_config/tk-multi-publish2

    tk-multi-loader2:
      action_mappings:
        Maya Scene: [reference, import]
        Photoshop Image: [texture_node]
        Rendered Image: [texture_node]
      actions_hook: '{self}/tk-maya_actions.py'
      entities:
      - caption: Current Project
        type: Hierarchy
        root: "/Project/{context.project.id}"
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [project, is, '{context.project}']
        - [task_assignees, is, '{context.user}']
        hierarchy: [entity, content]
      location:
        path: https://github.com/shotgunsoftware/tk-multi-loader2.git
        version: c6cfb186fcebd59d6ca933ce61835b797de44f21
        type: git_branch
        branch: develop/zero_config

    tk-multi-shotgunpanel:
      location:
        version: v1.3.0
        type: app_store
        name: tk-multi-shotgunpanel
      actions_hook: '{self}/general_actions.py:{self}/tk-maya_actions.py'
      action_mappings:
        PublishedFile:
        - actions: [reference, import]
          filters: {published_file_type: Maya Scene}
        - actions: [texture_node]
          filters: {published_file_type: Rendered Image}
        - actions: [texture_node]
          filters: {published_file_type: Photoshop Image}
        - actions: [udim_texture_node]
          filters: {published_file_type: UDIM Image}
        - actions: [publish_clipboard]
          filters: {}
        Task:
        - actions: [assign_task, task_to_ip]
          filters: {}
        Version:
        - actions: [quicktime_clipboard, sequence_clipboard]
          filters: {}

  location:
    path: https://github.com/shotgunsoftware/tk-maya.git
    version: 67a0a9dce1e31d1f2b19caa7a2d8ce55730d16c1
    type: git_branch
    branch: develop/zero_config
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false



