# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/engines.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


maya.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/maya.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.file_publisher'
        - '@common.settings.tk-multi-publish2.version_creator'
        - name: Maya Scene Publisher
          hook: "{config}/tk-multi-publish2/maya.basic/file_publisher.py"
          settings: {}
        - name: Save the file to the next version
          hook: "{config}/tk-multi-publish2/maya.basic/version_up.py"
          settings: {}
      location: "@common.apps.tk-multi-publish2.location"

    tk-multi-loader2:
      action_mappings:
        Alembic Cache: [reference, import]
        Image: [texture_node, image_plane]
        Maya Scene: [reference, import]
        Photoshop Image: [texture_node, image_plane]
        Rendered Image: [texture_node, image_plane]
        Texture: [texture_node, image_plane]
      actions_hook: '{self}/tk-maya_actions.py'
      entities:
      - caption: Current Project
        type: Hierarchy
        root: "/Project/{context.project.id}"
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [project, is, '{context.project}']
        - [task_assignees, is, '{context.user}']
        hierarchy: [entity, content]
      # ignore publishes without a status. with zero config, it is very easy
      # to publish the same path multiple times. the default zero config publish
      # plugins will clear the status of previous publishes of the same path.
      # this filter means only the latest publish will be displayed.
      publish_filters: [["sg_status_list", "is_not", null]]
      location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel:
      actions_hook: '{self}/general_actions.py:{self}/tk-maya_actions.py'
      action_mappings:
        PublishedFile:
        - actions: [reference, import]
          filters: {published_file_type: Alembic Cache}
        - actions: [texture_node, image_plane]
          filters: {published_file_type: Image}
        - actions: [reference, import]
          filters: {published_file_type: Maya Scene}
        - actions: [texture_node, image_plane]
          filters: {published_file_type: Photoshop Image}
        - actions: [texture_node, image_plane]
          filters: {published_file_type: Rendered Image}
        - actions: [texture_node, image_plane]
          filters: {published_file_type: Texture}
        - actions: [publish_clipboard]
          filters: {}
        Task:
        - actions: [assign_task, task_to_ip]
          filters: {}
        Version:
        - actions: [quicktime_clipboard, sequence_clipboard]
          filters: {}
      enable_context_switch: true
      location: "@common.apps.tk-multi-shotgunpanel.location"


  location: "@common.engines.tk-maya.location"
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false


