# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/apps.yml


3dsmax.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      collector: "{config}/3dsmax/publish/collector.py"

      publish_plugins:
          - name: Publish to Shotgun
            hook: "{self}/file_publisher.py"
            settings:
              Publish all file types: false
              File Types:
              - [Nuke Script, nk]
              - [Photoshop Image, psd, psb]
              - [3dsmax Scene, max]
              - [Houdini Scene, hip]
              - [Maya Scene, ma, mb]
              - [Hiero Project, hrox]
              - [Alembic Cache]
              - [Rendered Image, dpx, exr]
              - [Texture, tiff, tx, tga, dds]
              - [Image, jpeg, jpg, png]

          - name: Send to Shotgun review
            hook: "{self}/version_creator.py"
            settings: {}

      location:
        type: app_store
        name: tk-multi-publish2
        version: v0.0.9

    tk-multi-loader2:
      action_mappings:
        3dsmax Scene: [import, reference]
        Alembic Cache: [import]
      actions_hook: '{self}/tk-3dsmaxplus_actions.py'
      download_thumbnails: true
      entities:
      - caption: Current Project
        type: Hierarchy
        root: "/Project/{context.project.id}"
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [project, is, '{context.project}']
        - [task_assignees, is, '{context.user}']
        hierarchy: [entity, content]
      location:
        path: https://github.com/shotgunsoftware/tk-multi-loader2.git
        version: c6cfb186fcebd59d6ca933ce61835b797de44f21
        type: git_branch
        branch: develop/zero_config

    tk-multi-shotgunpanel:
      location:
        version: v1.3.0
        type: app_store
        name: tk-multi-shotgunpanel
      shotgun_fields_hook: '{self}/shotgun_fields.py'
      actions_hook: '{self}/general_actions.py'
      action_mappings:
        PublishedFile:
        - actions:
          - publish_clipboard
          filters: {}
        Task:
        - actions:
          - assign_task
          - task_to_ip
          filters: {}
        Version:
        - actions:
          - quicktime_clipboard
          - sequence_clipboard
          filters: {}

  location:
    path: https://github.com/shotgunsoftware/tk-3dsmaxplus.git
    version: aa76fc8c1a87b518e623abdfead4ddd8b571c168
    type: git_branch
    branch: develop/zero_config
  menu_favourites: []
  launch_builtin_plugins: [basic]




