# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Houdini Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/engines.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


houdini.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      help_url: "@common.apps.tk-multi-publish2.help_url"
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/houdini.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.publish_file'
        - '@common.settings.tk-multi-publish2.upload_version'
        - name: Add version number to Houdini file name
          hook: "{config}/tk-multi-publish2/houdini.basic/start_version_control.py"
          settings: {}
        - name: Publish Houdini work file
          hook: "{config}/tk-multi-publish2/houdini.basic/publish_houdini_session.py"
          settings: {}
      location: "@common.apps.tk-multi-publish2.location"

    tk-multi-loader2:
        action_mappings:
          Alembic Cache: [import]
          Houdini Scene: [merge]
          Image: [file_cop]
          Photoshop Image: [file_cop]
          Rendered Image: [file_cop]
          Texture: [file_cop]
        actions_hook: '{self}/tk-houdini_actions.py'
        entities:
        - caption: Project
          type: Hierarchy
          root: "{context.project}"
          publish_filters: []
        - caption: My Tasks
          type: Query
          entity_type: Task
          filters:
          - [project, is, '{context.project}']
          - [task_assignees, is, '{context.user}']
          hierarchy: [project, entity, content]
        # ignore publishes without a status. with zero config, it is very easy
        # to publish the same path multiple times. the default zero config publish
        # plugins will clear the status of previous publishes of the same path.
        # this filter means only the latest publish will be displayed.
        publish_filters: [["sg_status_list", "is_not", null]]
        location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel:
        actions_hook: '{self}/general_actions.py:{self}/tk-houdini_actions.py'
        action_mappings:
          PublishedFile:
          - actions: [import]
            filters: {published_file_type: Alembic Cache}
          - actions: [merge]
            filters: {published_file_type: Houdini Scene}
          - actions: [file_cop]
            filters: {published_file_type: Image}
          - actions: [file_cop]
            filters: {published_file_type: Photoshop Image}
          - actions: [file_cop]
            filters: {published_file_type: Rendered Image}
          - actions: [file_cop]
            filters: {published_file_type: Texture}
          - actions: [publish_clipboard]
            filters: {}
          Task:
          - actions:
            - assign_task
            - task_to_ip
            filters: {}
          Version:
          - actions:
            - quicktime_clipboard
            - sequence_clipboard
            filters: {}
        enable_context_switch: true
        location: "@common.apps.tk-multi-shotgunpanel.location"

  location: "@common.engines.tk-houdini.location"
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false

