# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Houdini Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


houdini.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/houdini.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.file_publisher'
        - '@common.settings.tk-multi-publish2.version_creator'
        - name: Houdini Scene Publisher
          hook: "{config}/tk-multi-publish2/houdini.basic/file_publisher.py"
          settings: {}
        - name: Save the file to the next version
          hook: "{config}/tk-multi-publish2/houdini.basic/version_up.py"
          settings: {}
      location: "@common.apps.tk-multi-publish2.location"

    tk-multi-loader2:
        action_mappings:
          Alembic Cache: [import]
        actions_hook: '{self}/tk-houdini_actions.py'
        entities:
        - caption: Project
          type: Hierarchy
          root: /
          publish_filters: []
        - caption: My Tasks
          type: Query
          entity_type: Task
          filters:
          - [project, is, '{context.project}']
          - [task_assignees, is, '{context.user}']
          hierarchy: [project, entity, content]
        location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel:
        actions_hook: '{self}/general_actions.py'
        action_mappings:
          PublishedFile:
          - actions:
            - publish_clipboard
            filters: {}
          Task:
          - actions:
            - assign_task
            - task_to_ip
            filters: {}
          Version:
          - actions:
            - quicktime_clipboard
            - sequence_clipboard
            filters: {}
        enable_context_switch: true
        location: "@common.apps.tk-multi-shotgunpanel.location"

  location:
    path: https://github.com/shotgunsoftware/tk-houdini.git
    version: 1668744e9ee0d12bbdc0fba9b81fabed4edcbe64
    type: git_branch
    branch: develop/zero_config
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false

