# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Toolkit configuration to be loaded whenever an association with a
             project has been established.

includes:
- includes/houdini/project.yml
- includes/maya/project.yml
- includes/nuke/project.yml
- includes/flame/project.yml
- includes/desktop/project.yml
- includes/desktop2/all.yml
- includes/shell/project.yml
- includes/photoshopcc/project.yml
- includes/aftereffects/project.yml
- includes/3dsmax/project.yml
- includes/alias/project.yml
- includes/vred/project.yml
- includes/shotgun/all.yml

engines:
  tk-houdini: '@houdini.project'
  tk-maya: '@maya.project'
  tk-nuke: '@nuke.project'
  tk-nukestudio: '@nukestudio.project'
  tk-desktop: '@desktop.project'
  tk-desktop2: '@desktop2.all'
  tk-shell: '@shell.project'
  tk-photoshopcc: '@photoshopcc.project'
  tk-aftereffects: '@aftereffects.project'
  tk-3dsmaxplus: '@3dsmaxplus.project'
  tk-3dsmax: '@3dsmax.project'
  tk-shotgun: '@shotgun.all'
  tk-flame: '@flame.project'
  tk-alias: '@alias.project'
  tk-vred: '@vred.project'
