# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


nuke.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/nuke.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.file_publisher'
        - '@common.settings.tk-multi-publish2.version_creator'
        - name: Nuke Scene Publisher
          hook: "{config}/tk-multi-publish2/nuke.basic/script_publisher.py"
          settings: {}
      location:
        #type: app_store
        #name: tk-multi-publish2
        #version: v0.0.11
        type: dev
        path: /Users/josh/dev/sg/zero_config/tk-multi-publish2

    tk-multi-loader2:
      action_mappings:
        Nuke Script: [script_import]
        Rendered Image: [read_node]
        Alembic Cache: [read_node]
      actions_hook: '{self}/tk-nuke_actions.py'
      entities:
      - caption: Current Project
        type: Hierarchy
        root: "/Project/{context.project.id}"
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [project, is, '{context.project}']
        - [task_assignees, is, '{context.user}']
        hierarchy: [entity, content]
      location:
        path: https://github.com/shotgunsoftware/tk-multi-loader2.git
        version: c6cfb186fcebd59d6ca933ce61835b797de44f21
        type: git_branch
        branch: develop/zero_config

    tk-multi-shotgunpanel:
      location:
        version: v1.3.0
        type: app_store
        name: tk-multi-shotgunpanel
      action_mappings:
        PublishedFile:
        - actions: [read_node]
          filters: {published_file_type: Rendered Image}
        - actions: [script_import]
          filters: {published_file_type: Nuke Script}
        Task:
        - actions: [assign_task, task_to_ip]
          filters: {}
      actions_hook: '{self}/general_actions.py:{self}/tk-nuke_actions.py'

  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false

  location:
    path: https://github.com/shotgunsoftware/tk-nuke.git
    version: b4b339878efde21edbf1b98f606ad6f18d0e5906
    type: git_branch
    branch: develop/zero_config
