# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/engines.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml


nuke.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2:
      collector: "{config}/tk-multi-publish2/basic/collector.py:{config}/tk-multi-publish2/nuke.basic/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.file_publisher'
        - '@common.settings.tk-multi-publish2.version_creator'
        - name: Nuke Scene Publisher
          hook: "{config}/tk-multi-publish2/nuke.basic/nuke_script_publisher.py"
          settings: {}
        - name: Nuke Studio Project Publisher
          hook: "{config}/tk-multi-publish2/nuke.basic/nukestudio_project_publisher.py"
          settings: {}
        - name: Save the file to the next version
          hook: "{config}/tk-multi-publish2/nuke.basic/nuke_version_up.py"
          settings: {}
        - name: Save the file to the next version
          hook: "{config}/tk-multi-publish2/nuke.basic/nukestudio_version_up.py"
          settings: {}
      location: "@common.apps.tk-multi-publish2.location"

    tk-multi-loader2:
      action_mappings:
        Alembic Cache: [read_node]
        Image: [read_node]
        Movie: [read_node]
        Nuke Script: [script_import]
        NukeStudio Project: [open_project]
        Photoshop Image: [read_node]
        Rendered Image: [read_node]
        Texture: [read_node]
      actions_hook: '{self}/tk-nuke_actions.py'
      entities:
      - caption: Current Project
        type: Hierarchy
        root: "/Project/{context.project.id}"
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [project, is, '{context.project}']
        - [task_assignees, is, '{context.user}']
        hierarchy: [entity, content]
      location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel:
      action_mappings:
        PublishedFile:
        - actions: [read_node]
          filters: {published_file_type: Alembic Cache}
        - actions: [read_node]
          filters: {published_file_type: Image}
        - actions: [read_node]
          filters: {published_file_type: Movie}
        - actions: [script_import]
          filters: {published_file_type: Nuke Script}
        - actions: [open_project]
          filters: {published_file_type: NukeStudio Project}
        - actions: [read_node]
          filters: {published_file_type: Photoshop Image}
        - actions: [read_node]
          filters: {published_file_type: Rendered Image}
        - actions: [read_node]
          filters: {published_file_type: Texture}
        Task:
        - actions: [assign_task, task_to_ip]
          filters: {}
      actions_hook: '{self}/general_actions.py:{self}/tk-nuke_actions.py'
      enable_context_switch: true
      location: "@common.apps.tk-multi-shotgunpanel.location"

  location: "@common.engines.tk-nuke.location"
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false
