# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its site level configuration

includes:
- ../common/frameworks.yml
- ../common/apps.yml


nuke.site:
  apps:
  location:
    path: https://github.com/shotgunsoftware/tk-nuke.git
    version: 7fc3d0d7f5e41f1829b847fe0874596231f489dd
    type: git_branch
    branch: develop/zero_config
  menu_favourites: []
  run_at_startup:
  launch_builtin_plugin: basic
  automatic_context_switch: false


